### ISSUE TITLE
Nameless Travel Anchors cannot be found

### ISSUE THREAD

**Issue by NillerMedDild** [castcrafter/travel_anchors#10]
Again, title :D

![billede](https://user-images.githubusercontent.com/21295394/97640462-12784380-1a41-11eb-84fa-e0ce8edde275.png)

### Versions
Forge 1.16.3 34.1.25
TravelAnchors-2.1

**Comment by noeppi-noeppi** [comment]
This is intended. I'll make it clear in the GUI

**Comment by noeppi-noeppi** [comment]
Is now marked with a red text in the GUI
