### ISSUE TITLE
[Suggestion] Rework Range enchantment

### ISSUE THREAD

**Issue by Lykrast** [castcrafter/travel_anchors#11]
Currently, the Range enchantment is useless on any item that isn't the Travel Staff, unless they specifically have the Teleportation enchantment. That means it kinds of "pollutes" the enchantment pool as sometimes you get some Range when enchanting/getting loot but since you don't have Teleportation at the same time it's essentially useless.

Since Teleportation only got 1 level, I suggest instead of having Teleportation and Range, just have Teleportation have multiple levels, with higher levels increasing range. Like Teleportation I = old Teleportation, Teleportation II = old Teleportation + Range I and so on.

While that would prevent upgrading the range on the Travel Staff itself, maybe Range can be kept but make it only applicable on the Travel Staff (and have it unable to receive Teleportation).

**Comment by NeosGhost** [comment]
Not sure if this is a bug or intended but travel staff cannot be enchanted directly with the enchantment table.  

Version 2.1

**Comment by noeppi-noeppi** [comment]
Range can now only be enchanted to tools when they already have teleportation. So you need boks.
