### ISSUE TITLE
Teleportation Enchant allows you to teleport to out-of-range Travel Anchors

### ISSUE THREAD

**Issue by NillerMedDild** [castcrafter/travel_anchors#13]
**Describe the bug**
Either the teleportation enchant is bugged and allows travel to anchors outside of range, or the label breaks after a certain range.

**Video**
https://cdn.discordapp.com/attachments/621124399130476544/804241610669817866/2021-01-28_01-48-43.mp4

**Comment by SeaSaltStar** [comment]
The range enchant also allows for this same phenomena, that being that you can teleport to anchors without a label.

**Comment by noeppi-noeppi** [comment]
Oh I seem to have missed a notification for this issue. Which version are you using?

**Comment by NillerMedDild** [comment]
TravelAnchors-2.2 :)

**Comment by noeppi-noeppi** [comment]
Ok this is weird as I think it was fixed in 2.2. I am going to take a look at this again

**Comment by NillerMedDild** [comment]
I just double checked and I was wrong, TravelAnchors-2.2 does not have this bug, sorry! :)
