### ISSUE TITLE
travel anchors work to go up but not to go down (only travel ancor block)

### ISSUE THREAD

**Issue by AlleCraft-alterego** [castcrafter/travel_anchors#15]
travel anchors work to go up but not to go down (only travel ancor block)

exemple: https://youtu.be/vEaAFWGy9vU

**Comment by noeppi-noeppi** [comment]
Weird. I can't reproduce this, neither in singleplayer nor when playing on a dedicated server. What version of travel anchors and LibX are you using? And if they're the latest versions, can you try it with only those two mods installed?

**Comment by AlleCraft-alterego** [comment]
ok, sorry i have updated libx and now is fixed
