### ISSUE TITLE
If use wand or enchant on block on range don't teleport player

### ISSUE THREAD

**Issue by AlleCraft-alterego** [castcrafter/travel_anchors#17]
If use wand or enchant on block on range don't teleport player

**Comment by noeppi-noeppi** [comment]
Sorry, but what exactly do you mean?

**Comment by AlleCraft-alterego** [comment]
if shift right-click on the block (for exemple on 2 block of distnace from player) don't teleport player
wand or enchant work only if click air or travel anchors blocks

**Comment by noeppi-noeppi** [comment]
I have either still not understood what you mean or I was unable to reproduce the issue.

I think you meant that the travel staff or an item enchanted with the traveling enchantment can only do short range teleports when clicking into the air, not on a block. This was not reproducible for me.

**Comment by AlleCraft-alterego** [comment]
yes,but on the floor...... i use only :
minecraft : 1.16.5
forge : 36.0.42
travel anchors : 2.2
libX : 1.0.17
jei : 7.6.1.71
