### ISSUE TITLE
[1.16.5] Too high detection radius / hitobx

### ISSUE THREAD

**Issue by TheSnowyChickens** [castcrafter/travel_anchors#27]
Hello,

the detection hitbox from the TA teleport text is by far to high. (\/ picture, I hope I marked it understandable :D )
It is weird to click somewhere in the sky and then get teleported, without knowing what I have hovered over exactly.

![grafik](https://user-images.githubusercontent.com/29357962/124541958-c3ca4700-de22-11eb-8bd7-bcd6b95c0cfe.png)

It is maybe possible to reduce the hitbox ?

Travel Anchor: 2.4
LibX: 1.0.76
Forge: 36.1.32 (<- on client, server with .31)

Modpack: All the Mods 6 - To the Sky + tested in my mod testing modpack, with only classic mods like JEI, FancyMenu)

**Comment by noeppi-noeppi** [comment]
There literally is a config value for this.
