### ISSUE TITLE
Unable to Sneak to go down Travel Anchors in 'Elevator' mode if Sneak is bound to Equipment Compare's keybind

### ISSUE THREAD

**Issue by MuteTiefling** [castcrafter/travel_anchors#32]
https://github.com/NillerMedDild/Enigmatica6/issues/3381

Mod in question: https://www.curseforge.com/minecraft/mc-mods/equipment-compare

When the `Show Comparison Tooltip` function is bound to shift, your elevators no longer go down. Only up. 

Changing the keybind to something else allows your mod to work again. 

I'm reporting this to both mods as I have no idea where the break is. I will note that elevators from the [Open Block Elevator](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator) port have no such issue. 

Mod Versions: 
elevatorid-1.16.5-1.7.13
TravelAnchors-2.4
EquipmentCompare-1.16.5-1.2.4

**Comment by Darkere** [comment]
https://github.com/castcrafter/travel_anchors/blob/9534e45df6a9bf9944093a97f15373cdaa59952d/src/main/java/de/castcrafter/travel_anchors/EventListener.java#L98

Please also keep in mind that there are plenty of people that rebind sneaking to a different key.

**Comment by noeppi-noeppi** [comment]
@Darkere the field names says nothing about the actual key. It's just mojang naming stuff weirdly. It will use the sneak key binding, no matter what it is bound to.
