### ISSUE TITLE
[1.16.5] When two achors are aligned, can't tp to closer one

### ISSUE THREAD

**Issue by Rodg88** [castcrafter/travel_anchors#39]
When trying to teleport to an anchor which happens to have another anchor behind it which is in-line, you always seem to TP to the one that's furthest away, even if the closer one's name is highlighted. 

System details: https://gist.github.com/Rodg88/30b70c6a97a2a8f812bd29a35e6a7eb7
(forge-1.16.5-36.2.21, TravelAnchors-2.4.jar)

**Comment by fampat** [comment]
This is still the issue in the 1.18.1 (TravelAnchors-1.18.1-3.2.2.jar) version.
You alway TP to the most far away TP in line.
