### ISSUE TITLE
[Feature] Enchantment-Descriptions support for enchantments added by this mod.

### ISSUE THREAD

**Issue by Dutchs** [castcrafter/travel_anchors#46]
This would make for a nice QoL addition.

[Enchantment-Descriptions](https://minecraft.curseforge.com/projects/enchantment-descriptions)
It looks for these localization keys:
```
enchantment.travel_anchors.teleportation.desc
enchantment.travel_anchors.range.desc
```

**Comment by MelanX** [comment]
added
