### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Bipbip2109** [castcrafter/travel_anchors#48]
The texture is replaced with one from the fabric port of Create ( https://github.com/Fabricators-of-Create/Create ) strangely modified.

-Windows 11
  -Intel i3 9th gen
  -Nvidia GeForce RTX 2060 SUPER
  -Corsair Vengeance DDR4 16G 2400 Mhz
-Java 17.01
-Fabric loader 0.13.3
-Fabric API 0.50.0
-And a bunch of other mods including Sodium, Indium, Continuity, Enchanced Block Entities...

![2022-04-20_00 09 02](https://user-images.githubusercontent.com/88253359/164110111-dae72e7c-3cc9-4c54-9d6f-ebfb1e4c0fac.png)

**Comment by MelanX** [comment]
This is a Forge mod and has no support for Fabric.

**Comment by Bipbip2109** [comment]
The heck ? 
Then what mod did I install ???

**Comment by Bipbip2109** [comment]
Oh I found it wrong GitHub sorry.
