### ISSUE TITLE
1.18.2 Teleportation System Compat Issue

### ISSUE THREAD

**Issue by ghost** [castcrafter/travel_anchors#50]
I understand why this issue is happening.

Mob Grind Utilities has an item called the Ender Inhibitor. When this device is turned on, the Travel Anchors mod completely breaks. When the device is turn off, TA works just fine. I know this is because the ender teleportation system is used to facilitate the transportation, but I hope there is some way to make these two mods compatible with each other.

**Comment by noeppi-noeppi** [comment]
Works as intended on TravelAnchors. The event is fired to allow other mods to cancel it. You could maybe open an issue on MobGrindingUtils to exclude players from the inhibitor.

However, TravelAnchors behaves exactly as it was intended in this case.
