### ISSUE TITLE
feature request: don't disable travel anchor when block placed above them

### ISSUE THREAD

**Issue by BrettMoan** [castcrafter/travel_anchors#60]
as of the build for 1.18-3.3, the travel anchor will get disabled when a single block is placed above them. even if that block is a slab or carpet.

It would fantastic if instead of being disabled if a single block is above them, that instead we teleported to the block above that. this would allow us to hide travel anchors in the base without affecting the cosmetics in anyway, and also allow various tile entities (such as an enchanting table) to be used on the anchor for the visual when teleporting.

**Comment by noeppi-noeppi** [comment]
You can hold a block in the offhand and then click the anchor. The anchor will take the look of the held block. This should also work with some block entities, however they won't have special functionality.
