### ISSUE TITLE
Mob grinding utils ender inhibitor prevents anchor from working

### ISSUE THREAD

**Issue by hvdklauw** [castcrafter/travel_anchors#61]
Took me a long time to debug this (way too long tbh)

But the ender inhibitor from mob grinding utils also prevents you from teleporting away from a nearby travel anchor, teleporting to it is not a problem.

Once I figured it out it was kinda obvious, but also kinda annoying.

Modpack is Stoneblock 3.

**Comment by noeppi-noeppi** [comment]
This is intended behaviour but I can add a config option to disable it.
