### ISSUE TITLE
"No travel anchor found." occurs even when blocking with shield in off-hand

### ISSUE THREAD

**Issue by mnmt** [castcrafter/travel_anchors#65]
Using:

- minecraft 1.19.2
- forge 43.2.3
- travel anchors 1.19.2-4.1.2

I have enchanted my sword with the teleport and range III enchant, which is helpful both for zipping around my base's travel anchors and for the short range Sneak+Right-Click teleport.

However, when in combat, I also use a shield in my off-hand, and every time I right-click to block with the shield, the "No travel anchor found" message pops up. This has gotten pretty irritating and I almost wish I'd not enchanted it now!

For me it would be better if this message did not occur when a viable right-click action was taking place, or at least were suppressed when using shields.

More generally, I would be happy if there was a client-side config option for the message to be suppressed in all cases. 
Equally, the message could be suppressed for any items enchanted with Teleport, as these items are much more likely to be used for actions other than just teleporting.

**Comment by noeppi-noeppi** [comment]
This works as intended. The main hand action has priority over the offhand on right click, so it is checked first and a message is shown if no anchor is found.

**Comment by mnmt** [comment]
Thanks for taking a look at this nonetheless :)
