### ISSUE TITLE
[1.18.2]Bro fix teleport when two anchors are in a line and you are teleported to the far one

### ISSUE THREAD

**Issue by KaxelDreamhack123** [castcrafter/travel_anchors#73]
This problem has already been raised, but it remains on version 1.18.1. I placed a bunch of anchors at my base and I’m jumping like a hare on different anchors to get to the right one, and then after 10 different teleports. You have to calculate a certain angle on the screen in order to teleport to the desired one and this is not fun at all. 
I can notice that I have a Range 2 enchantment on my staff.

**Comment by noeppi-noeppi** [comment]
It has been fixed in the 1.19 version. 1.18.2 is no longer supported, sorry.
